name: Question
description: Anything that is not a bug report or a feature request, questions should be directed to our [discussion board](https://github.com/wix/stylable/discussions)
body: 
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
  - type: textarea
    id: general-description
    attributes:
      label: Describe your issue
      description: General description about the issue you would like to raise
      
