name: Question
description: Anything that is not a bug report or a feature request, questions should be directed to our [discussion board](https://github.com/wix/stylable/discussions)
body: 
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill this out!
